### ISSUE TITLE
Question about the upcoming channel bundling integration

### ISSUE THREAD

**Issue by HansJochens** [Kopano-dev/meet#13]
As it is statet in the blog-article "Top 10 things to ask about Kopano Meet" from April , 
Kopano Meet does not support channel bundling and that there is work on a service for it. 
Until it is ready, the Meet connections will be directly point-to-point between the devices. 

Is there an actual time frame for this feature? 

[](https://kopano.com/blog/top-10-things-to-ask-about-kopano-meet/)

**Comment by fbartels** [comment]
Hi @HansJochens,

I heard from our product team that you have also reached out via email and got an answer there. Therefore I am closing this issue.
